import fs from "node:fs/promises";
import path from "node:path";
import type { MigrationTask } from "../shared/types";

const branchSummaryFiles = [
  "07-qwenvl-prompt-smoke-summary.json",
  "07-zimage-controlnet-smoke-summary.json",
  "07-flux2-refine-smoke-summary.json",
  "07-seedvr2-upscale-smoke-summary.json"
];

export async function ensureBranchSmokeAggregate(
  task: MigrationTask
): Promise<{ created: boolean; complete: boolean; path: string; reason: string }> {
  const reportPath = path.join(task.artifactPath, "07-first-stage-smoke.md");
  if (await isNonEmpty(reportPath)) {
    return {
      created: false,
      complete: true,
      path: reportPath,
      reason: "07-first-stage-smoke.md already exists"
    };
  }

  const summaries = [];
  for (const fileName of branchSummaryFiles) {
    const fullPath = path.join(task.artifactPath, fileName);
    const summary = await readJson<Record<string, unknown>>(fullPath);
    if (!summary) {
      return {
        created: false,
        complete: false,
        path: reportPath,
        reason: `Missing branch summary ${fileName}`
      };
    }
    summaries.push({ fileName, summary });
  }

  const incomplete = summaries.filter(({ summary }) => summary.status !== "pass");
  if (incomplete.length > 0) {
    return {
      created: false,
      complete: false,
      path: reportPath,
      reason: `Branch summaries not all pass: ${incomplete.map((item) => item.fileName).join(", ")}`
    };
  }

  const mediaIntegrityPath = path.join(task.artifactPath, "07-media-integrity.json");
  const mediaIntegrity = await readOptional(mediaIntegrityPath);
  const content = [
    "# 07 - First-stage branch smoke validation",
    "",
    `task_id: \`${task.id}\``,
    `workflow: \`${task.workflowPath}\``,
    `artifact_folder: \`${task.artifactPath}\``,
    "",
    "## Status",
    "",
    "Status: complete",
    "",
    "All first-stage branch smoke summaries are present and marked `pass`. This aggregate was generated by the demo orchestrator from durable branch evidence so the step can complete even if the SDK session continues emitting text after the required evidence exists.",
    "",
    "## Branch results",
    "",
    "| Branch | Summary artifact | Status | Output node(s) | Evidence |",
    "| --- | --- | --- | --- | --- |",
    ...summaries.map(({ fileName, summary }) => {
      const branch = stringValue(summary.branch) ?? fileName.replace(/^07-/, "").replace(/-smoke-summary\.json$/, "");
      const status = stringValue(summary.status) ?? "unknown";
      const outputNode = stringValue(summary.output_node) ?? "unknown";
      const evidenceFile = fileName.replace("-summary.json", "-evidence.json");
      return `| \`${branch}\` | \`${fileName}\` | \`${status}\` | \`${outputNode}\` | \`${evidenceFile}\` |`;
    }),
    "",
    "## Media integrity",
    "",
    mediaIntegrity ? "`07-media-integrity.json` is present." : "`07-media-integrity.json` was not present at aggregation time.",
    "",
    "## Boundary",
    "",
    "- Source workflow was not modified in place.",
    "- This step validates reduced/branch smoke evidence only; full workflow validation remains Step 08.",
    "- Do not treat this aggregate as permission to bypass or remove nodes."
  ].join("\n");

  await fs.writeFile(reportPath, `${content}\n`, "utf8");
  return {
    created: true,
    complete: true,
    path: reportPath,
    reason: "All Step 07 branch summaries are pass; aggregate created"
  };
}

async function readJson<T>(filePath: string): Promise<T | undefined> {
  const content = await readOptional(filePath);
  return content ? (JSON.parse(content) as T) : undefined;
}

async function readOptional(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "";
    throw error;
  }
}

async function isNonEmpty(filePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(filePath);
    return stat.isFile() && stat.size > 0;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}
