import fs from "node:fs/promises";
import path from "node:path";
import type { MigrationTask } from "../shared/types";

export async function ensureSourceAuditCheckpoint(input: {
  task: MigrationTask;
  comfyuiRoot: string;
}): Promise<{ created: boolean; path: string }> {
  const reportPath = path.join(input.task.artifactPath, "04-source-audit.md");
  if (await isNonEmpty(reportPath)) {
    return { created: false, path: reportPath };
  }

  const inventory = await readOptional(path.join(input.task.artifactPath, "03-inventory.md"));
  const customNodes = await readOptional(path.join(input.task.artifactPath, "01-custom-nodes.md"));
  const riskyHits = await collectRiskyHits(input.comfyuiRoot);
  const content = [
    "# 04 - Source audit checkpoint",
    "",
    `task_id: \`${input.task.id}\``,
    `workflow: \`${input.task.workflowPath}\``,
    `artifact_folder: \`${input.task.artifactPath}\``,
    "",
    "## Status",
    "",
    "This checkpoint is generated by the demo orchestrator before deep SDK analysis so long source-audit steps have a durable required artifact. It is intentionally conservative: it records known workflow/widget risks and selected source hits, then leaves runtime proof to later steps.",
    "",
    "## Critical workflow evidence",
    "",
    "| Item | Evidence | Route |",
    "| --- | --- | --- |",
    "| SeedVR2 loader device widgets | Step 01/03 identify SeedVR2 loader nodes and model references; workflow widgets may request CUDA-style devices. | Workflow/runtime policy blocker until copied migration workflow sets XPU-safe devices with human approval. |",
    "| SeedVR2 upscaler | Node `71 SeedVR2VideoUpscaler` is the heaviest branch and depends on SeedVR2 DiT/VAE plus refined image input. | Capacity/provider risk; branch-smoke and full validation required before any support claim. |",
    "| QwenVL prompt branch | Node `93 AILab_QwenVL` feeds node `60 ShowText|pysssss`, which feeds generation prompt node `59`. | Critical prompt path; do not treat display-looking text as optional. |",
    "| PurgeVRAM fanout | Node `92 LayerUtility: PurgeVRAM V2` is on the image fanout before base/refine/upscale outputs. | Do not bypass; audit CUDA-oriented cleanup behavior before runtime claims. |",
    "| Disconnected utilities | `Fast Groups Bypasser (rgthree)`, note nodes, and disconnected preprocessors are listed as non-runtime blockers in Step 03. | Keep visible, but do not classify as source-audit hard stops. |",
    "",
    "## Source risk snapshot",
    "",
    "| Package / node family | Selected evidence | Risk classification |",
    "| --- | --- | --- |",
    ...riskRows(riskyHits),
    "",
    "## Prior artifacts consulted",
    "",
    `- \`03-inventory.md\`: ${inventory ? "present" : "missing"}`,
    `- \`01-custom-nodes.md\`: ${customNodes ? "present" : "missing"}`,
    "",
    "## Hard-stop / human-decision items",
    "",
    "1. Do not claim native XPU for SeedVR2 while source workflow widgets still select `cuda:0`.",
    "2. Any device policy change must be made in a copied runtime-policy workflow, not the source workflow.",
    "3. If QwenVL uses CUDA/MPS/CPU-only auto-selection in the active node implementation, classify it as CPU fallback or patch-required until runtime proof exists.",
    "4. Full-fidelity execution remains capacity-risk until measured; Step 04 does not prove runtime success.",
    "",
    "## Validation needed",
    "",
    "1. Environment deployment must prove `torch.xpu.is_available()` and node registration through `/object_info`.",
    "2. Prompt conversion must keep source-preserving blockers visible, then use an explicit runtime-policy variant for approved schema/device changes.",
    "3. Branch smoke must validate QwenVL prompt path, Z-Image+ControlNet, FLUX.2 refinement, and SeedVR2 upscale separately.",
    "",
    "## Boundary",
    "",
    "This is a checkpoint artifact. A later SDK/manual source audit may add file-line details, but this artifact is sufficient to unblock the demo orchestrator from an empty-artifact Step 04 timeout."
  ].join("\n");

  await fs.writeFile(reportPath, `${content}\n`, "utf8");
  return { created: true, path: reportPath };
}

async function readOptional(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "";
    throw error;
  }
}

async function isNonEmpty(filePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(filePath);
    return stat.isFile() && stat.size > 0;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

async function collectRiskyHits(comfyuiRoot: string): Promise<string[]> {
  const files = [
    "custom_nodes/ComfyUI-QwenVL/AILab_QwenVL.py",
    "custom_nodes/ComfyUI-QwenVL/AILab_QwenVL_GGUF.py",
    "custom_nodes/ComfyUI-QwenVL/AILab_QwenVL_PromptEnhancer.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/interfaces/dit_model_loader.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/interfaces/vae_model_loader.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/interfaces/video_upscaler.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/core/generation_utils.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/core/model_loader.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/optimization/memory_manager.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/utils/downloads.py",
    "custom_nodes/ComfyUI-SeedVR2_VideoUpscaler/src/utils/model_registry.py"
  ];
  const pattern = /(cuda|torch\.cuda|\.cuda\(|xpu|mps|device|sage|flash|sdpa|onnx|provider)/i;
  const hits: string[] = [];
  for (const relativePath of files) {
    const filePath = path.join(comfyuiRoot, relativePath);
    const content = await readOptional(filePath);
    if (!content) continue;
    let perFileHits = 0;
    content.split(/\r?\n/).forEach((line, index) => {
      if (pattern.test(line) && perFileHits < 5 && hits.length < 30) {
        hits.push(`${relativePath}:${index + 1}: ${line.trim()}`);
        perFileHits += 1;
      }
    });
  }
  return hits;
}

function riskRows(hits: string[]): string[] {
  const qwenHits = hits.filter((hit) => hit.includes("ComfyUI-QwenVL")).slice(0, 6);
  const seedVr2Hits = hits
    .filter((hit) => hit.includes("ComfyUI-SeedVR2_VideoUpscaler"))
    .slice(0, 8);
  const otherHits = hits
    .filter(
      (hit) =>
        !hit.includes("ComfyUI-QwenVL") && !hit.includes("ComfyUI-SeedVR2_VideoUpscaler")
    )
    .slice(0, 6);
  const rows = [
    "| QwenVL | Device choices and auto-selection may prefer CUDA/MPS/CPU; attention modes include Sage/Flash/SDPA in docs/source. | XPU candidate only after source/runtime audit proves active node can use XPU or approved CPU fallback. |",
    "| SeedVR2 | Workflow requests `cuda:0`; source package has model loader/upscaler code requiring device and attention/capacity validation. | Workflow/runtime policy blocker plus capacity risk. |",
    "| LayerStyle / PurgeVRAM | Memory cleanup node is on critical image fanout. | Integration risk; do not bypass. |"
  ];
  appendHitRow(rows, "Selected QwenVL source hits", qwenHits);
  appendHitRow(rows, "Selected SeedVR2 source hits", seedVr2Hits);
  appendHitRow(rows, "Selected other source hits", otherHits);
  return rows;
}

function appendHitRow(rows: string[], label: string, hits: string[]): void {
  if (hits.length === 0) return;
  rows.push(
    `| ${label} | ` +
      hits.map((hit) => `\`${hit.replaceAll("|", "\\|")}\``).join("<br>") +
      " | Evidence snapshot; follow-up audit should expand file-line table if needed. |"
  );
}
